version: "3"

services:
  productosapp:
    container_name: "backendproducts"
    build: .
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/productos
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "productos"
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  mysql-data:
    external: false
